FROM seminlev/php-base

RUN apt-get update && apt-get install -y openssh-server                                                                                                                                                                              
RUN mkdir /var/run/sshd                                                                                                                                                                                                              
RUN echo 'root:root' | chpasswd                                                                                                                                                                                                
RUN echo 'www-data:www-data' | chpasswd                                                                                                                                                                                            
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config                                                                                                                                            
RUN echo -n "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp256\
    ,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256\
    ,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" >> /etc/ssh/sshd_config
RUN echo 'AllowUsers www-data' >> /etc/ssh/sshd_config
                                                                                                                                                                                                                                     
# SSH login fix. Otherwise user is kicked off after login                                                                                                                                                                            
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd                                                                                                                               
ENV NOTVISIBLE "in users profile"                                                                                                                                                                                                    
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22                                                                                                                                                                                        
                                                                                                                                                                                                                                     
