FROM seminlev/php-base

#Composer                                                                                                     
RUN php -r "readfile('https://getcomposer.org/installer');" | php -- --filename=composer -- --install-dir=bin
